### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by gootik** [fenollp/erlscp#14]
Hi Pierre,
I'd like to help you with this project, and I'm sure others do too. But I'm not sure where you need help or what's left to do. If you can create Github issues or a list of to-dos, people can easily contribute.

Thanks

**Comment by fenollp** [comment]
Hey!
So I don't have a precise TODO list. I hoped that there would be enough information on the README for people to get started.
I would happily review PRs time permitting :)

First step should be to fix the test suite: I removed testing of older releases even though this project works for them. It was just easier to skip some older releases when testing code generation.
